name: Docker Image CI

on:
  push:
    branches: [ "A beautiful watercolor poster featuring Chung-Hung Zhong enjoying delicious food." ]
  pull_request:
    branches: [ "Next to the food, there is a bottle of incredibly tasty chili sauce. " ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
